
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class BuildingEntry : Luban.BeanBase
{
    public BuildingEntry(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("id");
        Type = (EPOIType)(int)_obj.GetValue("type");
        PerFamilies = (int)_obj.GetValue("perFamilies");
        Min = (int)_obj.GetValue("min");
        Max = (int)_obj.GetValue("max");
        SizeW = (int)_obj.GetValue("sizeW");
        SizeH = (int)_obj.GetValue("sizeH");
        PrefabId = (string)_obj.GetValue("prefabId");
        PrefabBasePath = (string)_obj.GetValue("prefabBasePath");
        Capacity = (int)_obj.GetValue("capacity");
        Zone = (string)_obj.GetValue("zone");
    }

    public static BuildingEntry DeserializeBuildingEntry(JToken _buf)
    {
        return new BuildingEntry(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 建筑类型
    /// </summary>
    public readonly EPOIType Type;
    /// <summary>
    /// 每N户家庭生成1个
    /// </summary>
    public readonly int PerFamilies;
    /// <summary>
    /// 最少生成数量
    /// </summary>
    public readonly int Min;
    /// <summary>
    /// 最多生成数量
    /// </summary>
    public readonly int Max;
    /// <summary>
    /// 占地宽(格)
    /// </summary>
    public readonly int SizeW;
    /// <summary>
    /// 占地高(格)
    /// </summary>
    public readonly int SizeH;
    /// <summary>
    /// prefab名称
    /// </summary>
    public readonly string PrefabId;
    /// <summary>
    /// prefab所在目录
    /// </summary>
    public readonly string PrefabBasePath;
    /// <summary>
    /// POI最大容纳NPC数
    /// </summary>
    public readonly int Capacity;
    /// <summary>
    /// 所属分区
    /// </summary>
    public readonly string Zone;


    public const int __ID__ = 394839550;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "perFamilies:" + PerFamilies + ","
        + "min:" + Min + ","
        + "max:" + Max + ","
        + "sizeW:" + SizeW + ","
        + "sizeH:" + SizeH + ","
        + "prefabId:" + PrefabId + ","
        + "prefabBasePath:" + PrefabBasePath + ","
        + "capacity:" + Capacity + ","
        + "zone:" + Zone + ","
        + "}";
    }
}
}

