
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EPOIType
    {
        House = 0,
        Farm = 1,
        Mine = 2,
        Forest = 3,
        Pond = 4,
        Market = 5,
        Recreation = 6,
    }

} 

