
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class PlacedItem : Luban.BeanBase
{
    public PlacedItem(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Path = (string)_obj.GetValue("path");
        CanPlace = (bool)_obj.GetValue("canPlace");
        CanRemove = (bool)_obj.GetValue("canRemove");
        Cost = (int)_obj.GetValue("cost");
        Description = (string)_obj.GetValue("description");
    }

    public static PlacedItem DeserializePlacedItem(JToken _buf)
    {
        return new PlacedItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 能否放置
    /// </summary>
    public readonly bool CanPlace;
    /// <summary>
    /// 能否移除
    /// </summary>
    public readonly bool CanRemove;
    /// <summary>
    /// 花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 1730850064;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "path:" + Path + ","
        + "canPlace:" + CanPlace + ","
        + "canRemove:" + CanRemove + ","
        + "cost:" + Cost + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

