
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public TbBuildingEntry TbBuildingEntry {get; }
    public TbPlacedItem TbPlacedItem {get; }
    public TbZoneRect TbZoneRect {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbBuildingEntry = new TbBuildingEntry(loader("tbbuildingentry"));
        TbPlacedItem = new TbPlacedItem(loader("tbplaceditem"));
        TbZoneRect = new TbZoneRect(loader("tbzonerect"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbBuildingEntry.ResolveRef(this);
        TbPlacedItem.ResolveRef(this);
        TbZoneRect.ResolveRef(this);
    }
}

}

