
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbBuildingEntry
{
    private readonly System.Collections.Generic.Dictionary<string, BuildingEntry> _dataMap;
    private readonly System.Collections.Generic.List<BuildingEntry> _dataList;
    
    public TbBuildingEntry(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, BuildingEntry>(_buf.Count);
        _dataList = new System.Collections.Generic.List<BuildingEntry>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            BuildingEntry _v;
            _v = global::cfg.BuildingEntry.DeserializeBuildingEntry(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, BuildingEntry> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildingEntry> DataList => _dataList;

    public BuildingEntry GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuildingEntry Get(string key) => _dataMap[key];
    public BuildingEntry this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

