
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbPlacedItem
{
    private readonly System.Collections.Generic.Dictionary<string, PlacedItem> _dataMap;
    private readonly System.Collections.Generic.List<PlacedItem> _dataList;
    
    public TbPlacedItem(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, PlacedItem>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PlacedItem>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PlacedItem _v;
            _v = global::cfg.PlacedItem.DeserializePlacedItem(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, PlacedItem> DataMap => _dataMap;
    public System.Collections.Generic.List<PlacedItem> DataList => _dataList;

    public PlacedItem GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlacedItem Get(string key) => _dataMap[key];
    public PlacedItem this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

