
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class ZoneRect : Luban.BeanBase
{
    public ZoneRect(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (string)_obj.GetValue("id");
        Zone = (string)_obj.GetValue("zone");
        StartX = (int)_obj.GetValue("startX");
        StartY = (int)_obj.GetValue("startY");
        EndX = (int)_obj.GetValue("endX");
        EndY = (int)_obj.GetValue("endY");
    }

    public static ZoneRect DeserializeZoneRect(JToken _buf)
    {
        return new ZoneRect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 分区名称(resource/public/residential)
    /// </summary>
    public readonly string Zone;
    /// <summary>
    /// 起始格X
    /// </summary>
    public readonly int StartX;
    /// <summary>
    /// 起始格Y
    /// </summary>
    public readonly int StartY;
    /// <summary>
    /// 结束格X
    /// </summary>
    public readonly int EndX;
    /// <summary>
    /// 结束格Y
    /// </summary>
    public readonly int EndY;


    public const int __ID__ = 912826320;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "zone:" + Zone + ","
        + "startX:" + StartX + ","
        + "startY:" + StartY + ","
        + "endX:" + EndX + ","
        + "endY:" + EndY + ","
        + "}";
    }
}
}

